-- CREATE DATABASE IF NOT EXISTS `${DB_NAME}`;
-- GRANT ALL ON `${DB_NAME}`.* TO '${MYSQL_USER}'@'%';

CREATE USER IF NOT EXISTS 'raccoon'@'%';
CREATE DATABASE IF NOT EXISTS `raccoondb`;
GRANT ALL PRIVILEGES ON `raccoondb`.* TO 'raccoon'@'%';
