language: java

jdk:
  - oraclejdk16

before_cache:
  - rm -rf $HOME/.m2/repository/**/*-SNAPSHOT

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.m2/wrapper"

script:
  - "./mvnw clean verify"
  - "cd quarkus.ls.ext/com.redhat.quarkus.ls && ./mvnw clean verify"

notifications:
  email: true