version: "3"

services:

  raccoon-mariadb:
    image: mariadb:10.8
    environment:
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_NAME}'
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d

  keycloak:
    # For amd64 CPUs:
#    image: quay.io/keycloak/keycloak:14.0.0
    # For arm CPUs:
    image: wizzn/keycloak:14
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak_init/realm-export.json
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ./keycloak_init/:/tmp/keycloak_init

  raccoon-elasticsearch:
    # For amd64 CPUs:
#    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    # For arm CPUs:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2-arm64
    environment:
      discovery.type: single-node
    ports:
      - ${ELASTIC_PORT}:9200
