services:
  raccoon-mariadb:
    image: mariadb:10.8
    environment:
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_NAME}"
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d

  keycloak:
    image: quay.io/keycloak/keycloak:24.0.4
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak_init/realm-export.json
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ./keycloak_init/:/tmp/keycloak_init
    command: start-dev

  raccoon-elasticsearch:
    # For amd64 CPUs:
    #    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    # For arm CPUs:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2-arm64
    environment:
      discovery.type: single-node
    ports:
      - ${ELASTIC_PORT}:9200

volumes:
  postgres_data:
