version: "3"

services:

  raccoon-mariadb:
    image: mariadb:10.5.6
    environment:
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_NAME}'
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d

  keycloak:
#    image: quay.io/keycloak/keycloak:14.0.0
    image: wizzn/keycloak:14
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/keycloak_init/realm-export.json
    ports:
      - ${KEYCLOAK_PORT}:8080
    volumes:
      - ./keycloak_init/:/tmp/keycloak_init
