version: "3"

services:
  raccoon-mariadb:
    image: mariadb:10.5.6
    environment:
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_NAME}'
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./db_init/:/docker-entrypoint-initdb.d

  raccoon-adminer:
    image: adminer:4.7.8
    depends_on:
      - raccoon-mariadb
    environment:
      ADMINER_DEFAULT_DB_DRIVER: mysql
      ADMINER_DEFAULT_DB_HOST: com.raccoon-mariadb
      ADMINER_DEFAULT_DB_NAME: releases
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: tables-filter tinymce
    ports:
      - 8888:8080